# Generated by Django 5.2.4 on 2025-07-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('ด้านสมรรถนะและมาตรฐานตามตำแหน่ง', 'ด้านสมรรถนะและมาตรฐานตามตำแหน่ง'), ('ด้านทักษะดิจิทัล', 'ด้านทักษะดิจิทัล'), ('ด้านการบริหารความเสี่ยง', 'ด้านการบริหารความเสี่ยง')], max_length=50)),
                ('hours', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('certificate', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
